version: 2
updates:
  # Maintain GitHub Actions (e.g. actions/checkout, actions/upload-artifact)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Git Submodules (e.g. themes/PaperMod)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
